In [6]:
from morphology import *

In [7]:
from itkwidgets import view

path = r"C:\Users\admin\bric-morphology\studies\1\data\Lesion.nii"
d = run(path)
print(d)

img = nib.load(path)
mri_3d_voxels = img.get_fdata()
mri_3d_voxels[mri_3d_voxels > 0] = 255



Curvature:
Describe:
Gaussian curvature: DescribeResult(nobs=11933, minmax=(masked_array(data=-534.30273344,
             mask=False,
       fill_value=1e+20), masked_array(data=209.231522,
             mask=False,
       fill_value=1e+20)), mean=-0.13310002783306962, variance=48.37509187565998, skewness=masked_array(data=-41.43974706,
             mask=False,
       fill_value=1e+20), kurtosis=3205.1453258838815)
Mean Curvature: DescribeResult(nobs=11933, minmax=(masked_array(data=-175686.71095159,
             mask=False,
       fill_value=1e+20), masked_array(data=117845.2614735,
             mask=False,
       fill_value=1e+20)), mean=-19.107660895902086, variance=5780512.834950684, skewness=masked_array(data=-21.90259677,
             mask=False,
       fill_value=1e+20), kurtosis=3038.6368772320093)
Principal Curvature Min: DescribeResult(nobs=11922, minmax=(masked_array(data=-351373.42190229,
             mask=False,
       fill_value=1e+20), masked_array(data=1.72062666,
      

In [8]:
view(mri_3d_voxels)

Viewer(geometries=[], gradient_opacity=0.22, point_sets=[], rendered_image=<itk.itkImagePython.itkImageD3; pro…

In [9]:
s  =np.nan_to_num(d.surface_measures.sharpness)

In [10]:
s

array([[1.18233244e+01, 6.01723703e+02, 1.21743890e-01, ...,
        3.91172170e+00, 3.69177291e-04, 9.62231293e-06],
       [3.15501807e-01, 7.44030805e-04, 1.29735853e-03, ...,
        4.57866585e-03, 5.09505946e-02, 9.99788465e-03],
       [6.75889548e-02, 8.79120270e-02, 5.04215630e-01, ...,
        5.12877865e-03, 2.92818317e-03, 1.38267673e-03],
       ...,
       [8.99887340e-02, 8.74551848e-02, 8.58047830e-02, ...,
        1.35446412e-04, 9.22135672e-03, 9.73047229e-01],
       [1.59859199e+02, 1.83451798e-04, 1.36921182e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [13]:
from sklearn.preprocessing import MinMaxScaler
r,c = d.isosurface.verts.shape
s = np.nan_to_num(d.surface_measures.sharpness)
scaler = MinMaxScaler()
scaler.fit(s)
s_normalized= scaler.transform(s)

opacities = s_normalized.flatten()[0:r+1]
opacities.shape

(11933,)

In [15]:
arrs = [np.array([x]) for x in d.isosurface.verts.tolist()]

In [16]:
n = 3
view(point_sets=arrs[0:n])

Viewer(geometries=[], gradient_opacity=0.22, point_set_colors=array([[0.8392157 , 0.        , 0.        ],
   …

In [76]:
arrs

[array([[ 49.90246201, 114.        ,  60.        ]]),
 array([[ 50.        , 114.        ,  59.54909897]]),
 array([[ 50.       , 113.6063385,  60.       ]]),
 array([[ 50.        , 113.24349976,  61.        ]]),
 array([[ 49.7934494, 114.       ,  61.       ]]),
 array([[ 50.        , 113.25534821,  62.        ]]),
 array([[ 49.7802124, 114.       ,  62.       ]]),
 array([[ 50.        , 113.50923157,  63.        ]]),
 array([[ 49.84498215, 114.        ,  63.        ]]),
 array([[ 50.        , 113.91691589,  64.        ]]),
 array([[ 49.97206497, 114.        ,  64.        ]]),
 array([[ 50.        , 114.        ,  64.15919495]]),
 array([[ 49.98955917, 115.        ,  59.        ]]),
 array([[ 50.        , 115.        ,  58.96845627]]),
 array([[ 50.        , 114.91832733,  59.        ]]),
 array([[ 49.75939178, 115.        ,  60.        ]]),
 array([[ 49.63499451, 115.        ,  61.        ]]),
 array([[ 49.60172653, 115.        ,  62.        ]]),
 array([[ 49.64076996, 115.        , 

In [12]:
import itk
# Segment the cells
smoothed = itk.smoothing_recursive_gaussian_image_filter(mri_3d_voxels)

thresholded = itk.moments_threshold_image_filter(smoothed,
                                                 inside_value=0,
                                                 outside_value=1)

connected_components = itk.connected_component_image_filter(thresholded)

In [13]:
view(label_image=connected_components)

Viewer(geometries=[], gradient_opacity=0.22, interpolation=False, point_sets=[], rendered_label_image=<itk.itk…

In [14]:
names = [(0, 'Background'), (1, 'First cell')]
viewer = view(smoothed,
              label_image=connected_components,
              label_image_names=names,
              label_image_blend=0.8,
              rotate=True,
              gradient_opacity=0.5,
              slicing_planes=True)
viewer

Viewer(geometries=[], gradient_opacity=0.5, interpolation=False, label_image_blend=0.8, label_image_names=[(0,…

In [41]:
import itkwidgets
itkwidgets.line_profile(mri_3d_voxels)

In [47]:
itkwidgets.checkerboard(mri_3d_voxels, mri_3d_voxels)

In [49]:
d.isosurface.verts.shape

(11932, 3)

[[49.902462005615234, 114.0, 60.0],
 [50.0, 114.0, 59.54909896850586],
 [50.0, 113.60633850097656, 60.0],
 [50.0, 113.24349975585938, 61.0],
 [49.79344940185547, 114.0, 61.0],
 [50.0, 113.2553482055664, 62.0],
 [49.78021240234375, 114.0, 62.0],
 [50.0, 113.50923156738281, 63.0],
 [49.8449821472168, 114.0, 63.0],
 [50.0, 113.91691589355469, 64.0],
 [49.97206497192383, 114.0, 64.0],
 [50.0, 114.0, 64.15919494628906],
 [49.989559173583984, 115.0, 59.0],
 [50.0, 115.0, 58.96845626831055],
 [50.0, 114.91832733154297, 59.0],
 [49.75939178466797, 115.0, 60.0],
 [49.63499450683594, 115.0, 61.0],
 [49.60172653198242, 115.0, 62.0],
 [49.640769958496094, 115.0, 63.0],
 [49.73752212524414, 115.0, 64.0],
 [50.0, 114.57132720947266, 65.0],
 [49.8868293762207, 115.0, 65.0],
 [50.0, 115.0, 65.55415344238281],
 [49.976806640625, 116.0, 59.0],
 [50.0, 116.0, 58.92947006225586],
 [49.74442672729492, 116.0, 60.0],
 [49.611331939697266, 116.0, 61.0],
 [49.56104278564453, 116.0, 62.0],
 [49.574398040771484,